package net.jasonshepherd.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-06-13T10:40:00.592+10:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "AustralianPostCodeHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AustralianPostCodeHttpPost {

    /**
     * Get Australian Location by partial / full Postcode
     */
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    @WebMethod(operationName = "GetAustralianLocationByPostCode")
    public java.lang.String getAustralianLocationByPostCode(
        @WebParam(partName = "PostCode", name = "PostCode", targetNamespace = "")
        java.lang.String postCode
    );

    /**
     * Get Australian Postcode by partial / full Location Name
     */
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    @WebMethod(operationName = "GetAustralianPostCodeByLocation")
    public java.lang.String getAustralianPostCodeByLocation(
        @WebParam(partName = "Location", name = "Location", targetNamespace = "")
        java.lang.String location
    );
}
